logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 2024
spring:
  application:
    name: 'BIDDING-SYSTEM'
    version: '0.0.1-SNAPSHOT'
  datasource:
    url: jdbc:mysql://localhost:3306/bidding_system
    username: root
    #password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000